# appveyor configuration
version: '{build}'

environment:
  matrix:
    - GENERATOR: Visual Studio 12 Win64
    - GENERATOR: Visual Studio 12

before_build:
  - cmake -DBUILD_SHARED_LIBS=ON -DBUILD_STATIC_LIBS=OFF -DBUILD_TESTS=OFF -DENABLE_SSL_SUPPORT=False -G"%GENERATOR%" .

build:
  project: ALL_BUILD.vcxproj
  verbosity: normal
